# Generated by Django 4.1.2 on 2022-11-21 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homeapp", "0003_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="plan_details",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elevation", models.ImageField(blank=True, null=True, upload_to="")),
                ("twod_plan", models.ImageField(blank=True, null=True, upload_to="")),
                ("threed_plan", models.ImageField(blank=True, null=True, upload_to="")),
                ("rooms", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
                ("area", models.CharField(max_length=1000)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_name",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
