# Generated by Django 4.1.2 on 2022-11-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeapp", "0004_plan_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan_details",
            name="area",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="plan_details",
            name="bathrooms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="plan_details",
            name="rooms",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
