# Generated by Django 4.1.2 on 2022-11-23 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "homeapp",
            "0005_alter_plan_details_area_alter_plan_details_bathrooms_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan_details",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_name",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
