# Generated by Django 4.1.2 on 2022-11-25 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homeapp", "0006_alter_plan_details_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="plan_request",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room", models.IntegerField(blank=True, null=True)),
                ("bath", models.IntegerField(blank=True, null=True)),
                ("area", models.CharField(blank=True, max_length=1000, null=True)),
                ("additional", models.TextField(blank=True, null=True)),
                ("budjet", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
