# Generated by Django 4.1.2 on 2022-11-29 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homeapp", "0007_plan_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan_request",
            name="company_name",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="homeapp.company",
            ),
        ),
    ]
