# Generated by Django 4.1.2 on 2022-12-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeapp", "0010_replyreq"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan_request",
            name="reply",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
